declare abstract class Game_CharacterBase {
  private x: number;
  private y: number;
  protected _x: number;
  protected _y: number;
  protected _realX: number;
  protected _realY: number;
  protected _moveSpeed: number;
  protected _moveFrequency: number;
  protected _opacity: number;
  protected _blendMode: number;
  protected _direction: number;
  protected _pattern: number;
  protected _priorityType: number;
  protected _tileId: number;
  protected _characterName: string;
  protected _characterIndex: number;
  protected _isObjectCharacter: boolean;
  protected _walkAnime: boolean;
  protected _stepAnime: boolean;
  protected _directionFix: boolean;
  protected _through: boolean;
  protected _transparent: boolean;
  protected _bushDepth: number;
  protected _animationId: number;
  protected _balloonId: number;
  protected _animationPlaying: boolean;
  protected _balloonPlaying: boolean;
  protected _animationCount: number;
  protected _stopCount: number;
  protected _jumpCount: number;
  protected _jumpPeak: number;
  protected _movementSuccess: boolean;
  
  constructor();

  public initialize(): void;
  public initMembers(): void;
  public pos(x: number, y: number): boolean;
  public posNt(x: number, y: number): boolean;
  public moveSpeed(): number;
  public setMoveSpeed(newMoveSpeed: number): void;
  public moveFrequency(): number;
  public setMoveFrequency(newMoveFrequency: number): void;
  public opacity(): number;
  public setOpacity(newOpacity: number): void;
  public blendMode(): number;
  public setBlendMode(newBlendMode: number): void;
  public isNormalPriority(): boolean;
  public setPriorityType(newPriorityType: number): void;
  public isMoving(): boolean;
  public isJumping(): boolean;
  public jumpHeight(): number;
  public isStopping(): boolean;
  public checkStop(threshold: number): boolean;
  public resetStopCount(): void;
  public realMoveSpeed(): number;
  public distancePerFrame(): number;
  public isDashing(): boolean;
  public isDebugThrough(): boolean;
  public straighten(): void;
  public reverseDir(currentDirection: number): number;
  public canPass(targetX: number, targetY: number, direction: number): boolean;
  public canPassDiagonally(targetX: number, targetY: number, compositeHorz: number, compositeVert: number): boolean;
  public isMapPassable(targetX: number, targetY: number, direction: number): boolean;
  public isCollidedWithCharacters(targetX: number, targetY: number): boolean;
  public isCollidedWithEvents(targetX: number, targetY: number): boolean;
  public isCollidedWithVehicles(targetX: number, targetY: number): boolean;
  public setPosition(x: number, y: number): void;
  public copyPosition(character: Game_CharacterBase): void;
  public locate(x: number, y: number): void;
  public direction(): number;
  public setDirection(newDirection: number): void;
  public isTile(): boolean;
  public isObjectCharacter(): boolean;
  public shiftY(): number;
  public scrolledX(): number;
  public scrolledY(): number;
  public screenX(): number;
  public screenY(): number;
  public screenZ(): number;
  public isNearTheScreen(): boolean;
  public update(): void;
  public updateStop(): void;
  public updateJump(): void;
  public updateMove(): void;
  public updateAnimation(): void;
  public animationWait(): number;
  public updateAnimationCount(): void;
  public updatePattern(): void;
  public maxPattern(): number;
  public pattern(): number;
  public setPattern(newPattern: number): void;
  public isOriginalPattern(): boolean;
  public resetPattern(): void;
  public refreshBushDepth(): void;
  public isOnLadder(): boolean;
  public isOnBush(): boolean;
  public terrainTag(): number;
  public regionId(): number;
  public increaseSteps(): void;
  public tileId(): number;
  public characterName(): string;
  public characterIndex(): number;
  public setImage(newCharacterName: string, newCharacterIndex: number): void;
  public setTileImage(newTileId: number): void;
  public checkEventTriggerTouchFront(direction: number): void;
  public checkEventTriggerTouch(x?: number, y?: number): void;
  public isMovementSucceeded(): boolean;
  public setMovementSuccess(isSuccess: boolean): void;
  public moveStraight(direction: number): void;
  public moveDiagonally(compositeHorz: number, compositeVert: number): void;
  public jump(xModifier: number, yModifier: number): void;
  public hasWalkAnime(): boolean;
  public setWalkAnime(useWalkAnimation: boolean): void;
  public hasStepAnime(): boolean;
  public setStepAnime(useStepAnimation: boolean): void;
  public isDirectionFixed(): boolean;
  public setDirectionFix(isDirectionFixed: boolean): void;
  public isThrough(): boolean;
  public setThrough(isThrough: boolean): void;
  public isTransparent(): boolean;
  public bushDepth(): number;
  public setTransparent(isTransparent: boolean): void;
  public startAnime(): void;
  public startBalloon(): void;
  public isAnimationPlaying(): boolean;
  public isBalloonPlaying(): boolean;
  public endAnimation(): void;
  public endBalloon(): void;
}

export { Game_CharacterBase };